defaults:
  - _self_
  - callbacks: callbacks
  - private: default
  - datamodule: amazon_reviews_sa
  - inference: basic
  - logging: wandb
  - loss: cross_entropy
  - metric: accuracy
  - model: basic_bert_model
  - optimizer: adamw
  - scheduler: linearwithwarmup
  - trainer: default_trainer
  - training: sa_training
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  run_name: Basic_model_el_cell
  logs_folder_name: logs
  workspace: dmiai-mh
  project_name: sentiment-analysis-tests
  device: cpu
  log_code: True
  save_pytorch_model: True
  save_best: True
  convert_to_jit: True
  predict: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}_${datamodule.fold_n}
