defaults:
  - _self_
  - callbacks: callbacks
  - datamodule: amazon_reviews_sa
  - inference: basic
  - logging: loggers
  - loss: NLLLoss
  - metric: accuracy
  - model: basic_bert_model
  - optimizer: adamw
  - scheduler: plateau
  - trainer: default_trainer
  - training: sa_training
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  logs_folder_name: logs
  workspace: erlemar
  project_name: dl_pipeline
  device: cpu
  log_code: False
  save_pytorch_model: True
  save_best: True
  convert_to_jit: True
  predict: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}_${datamodule.fold_n}
